<template>
    <v-app style="color:#1f2630;height:300px" >
        <views-navigation :color="color" :flat="flat" />
        <div >
            <section style="background-color:#1f2630" class="hero-section" id="privacy"  v-if="!userId">
                <v-container>
                    <v-row justify="center" class="align-items-center">
                        
                                <center><h3 style="color: rgba(248, 217, 75, 0.8);">Privacy Policy</h3></center> 
                           
                                <h4 style="color: rgba(248, 217, 75, 0.8);">Last updated: March 05, 2021</h4>




                               <span style="color:white">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.

                                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.

                                Interpretation and Definitions

                                <h4 style="color: rgba(248, 217, 75, 0.8); margin-top:10px ">Interpretation</h4>

                                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

                                <h4 style="color: rgba(248, 217, 75, 0.8); margin-top:10px ">Definitions</h4>

                               <h5 style="color: rgba(248, 217, 75, 0.8);margin-top:10px"> For the purposes of this Privacy Policy:</h5>

                                Account means a unique account created for You to access our Service or parts of our Service.

                                <br style="color:454545"><br style="color:454545">Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.

                               <br style="color:454545"><br style="color:454545"> Application means the software program provided by the Company downloaded by You on any electronic device, named lucky club

                               <br style="color:454545"><br style="color:454545"> Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to lucky club.

                               <br style="color:454545"><br style="color:454545"> Country refers to: California, United States

                               <br style="color:454545"><br style="color:454545"> Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.

                               <br style="color:454545"><br style="color:454545"> Personal Data is any information that relates to an identified or identifiable individual.

                                <br style="color:454545"><br style="color:454545">Service refers to the Application.

                                <br style="color:454545"><br style="color:454545">Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.

                                <br style="color:454545"><br style="color:454545">Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.

                                <br style="color:454545"><br style="color:454545">Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).

                                <br style="color:454545"><br style="color:454545">You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.

                                <h4 style="color: rgba(248, 217, 75, 0.8); margin-top:10px ">Collecting and Using Your Personal Data</h4>

                                <h4 style="color: rgba(248, 217, 75, 0.8); margin-top:10px ">Types of Data Collected</h4>

                                <h5 style="color: rgba(248, 217, 75, 0.8);margin-top:10px">Personal Data</h5>

                                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:

                                <br style="color:454545">First name and last name

                                <br style="color:454545">Usage Data

                                <br style="color:454545">Usage Data

                                <br style="color:454545">Usage Data is collected automatically when using the Service.

                                <br style="color:454545">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.

                                <br style="color:454545"><br style="color:454545">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.

                                <br style="color:454545"><br style="color:454545">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.

                                <h4 style="color: rgba(248, 217, 75, 0.8); margin-top:10px ">Information Collected while Using the Application</h4>

                                <br style="color:454545"><br style="color:454545">While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:

                                <br style="color:454545"><br style="color:454545">Pictures and other information from your Device's camera and photo library

                                <br style="color:454545"><br style="color:454545">We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.

                                <br style="color:454545"><br style="color:454545">You can enable or disable access to this information at any time, through Your Device settings.

                                <h5 style="color: rgba(248, 217, 75, 0.8);margin-top:10px">Use of Your Personal Data</h5>

                                <br style="color:454545"><br style="color:454545">The Company may use Personal Data for the following purposes:

                                <br style="color:454545"><br style="color:454545">To provide and maintain our Service, including to monitor the usage of our Service.

                                <br style="color:454545"><br style="color:454545">To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.

                                <br style="color:454545"><br style="color:454545">For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.

                                <br style="color:454545"><br style="color:454545">To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.

                                <br style="color:454545"><br style="color:454545">To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.

                                <br style="color:454545"><br style="color:454545">To manage Your requests: To attend and manage Your requests to Us.

                                For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.

                                <br style="color:454545"><br style="color:454545">For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.

                                <br style="color:454545"><br style="color:454545">We may share Your personal information in the following situations:

                                <br style="color:454545"><br style="color:454545">Retention of Your Personal Data

                                <br style="color:454545"><br style="color:454545">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.

                                <br style="color:454545"><br style="color:454545">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.

                                <br style="color:454545"><br style="color:454545">Transfer of Your Personal Data

                                <br style="color:454545"><br style="color:454545">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.

                                <br style="color:454545"><br style="color:454545">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.

                                <br style="color:454545"><br style="color:454545">The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.

                                <br style="color:454545"><br style="color:454545">Disclosure of Your Personal Data

                                <br style="color:454545"><br style="color:454545">Business Transactions

                                <br style="color:454545"><br style="color:454545">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.

                                <br style="color:454545"><br style="color:454545">Law enforcement

                                <br style="color:454545"><br style="color:454545">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).

                                <br style="color:454545"><br style="color:454545">Other legal requirements

                                <br style="color:454545"><br style="color:454545">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:

                                <br style="color:454545"><br style="color:454545">Comply with a legal obligation

                                <br style="color:454545"><br style="color:454545">Protect and defend the rights or property of the Company

                                <br style="color:454545"><br style="color:454545">Prevent or investigate possible wrongdoing in connection with the Service

                                <br style="color:454545"><br style="color:454545">Protect the personal safety of Users of the Service or the public

                                <br style="color:454545"><br style="color:454545">Protect against legal liability

                                <br style="color:454545"><br style="color:454545">Security of Your Personal Data

                                <br style="color:454545"><br style="color:454545">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.

                                <br style="color:454545"><br style="color:454545">Children's Privacy

                                <br style="color:454545"><br style="color:454545">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.

                                <br style="color:454545"><br style="color:454545">If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.

                                <br style="color:454545"><br style="color:454545">Links to Other Websites

                                <br style="color:454545"><br style="color:454545">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.

                                <br style="color:454545"><br style="color:454545">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.

                                <br style="color:454545"><br style="color:454545">Changes to this Privacy Policy

                               <br style="color:454545"><br style="color:454545"> We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.

                                <br style="color:454545"><br style="color:454545">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.

                                <br style="color:454545"><br style="color:454545">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

                                <br style="color:454545"><br style="color:454545">Contact Us

                                <br style="color:454545"><br style="color:454545">If you have any questions about this Privacy Policy, You can contact us:

                                By email: <a href = "mailto: elprofessorcapone@gmail.com">elprofessorcapone@gmail.com</a> 
                                </span> 
                    </v-row>
                </v-container>
            </section>
           
            <!-- End Hero -->
        </div>
        <v-scale-transition>
            <v-btn
                fab
                v-show="fab"
                v-scroll="onScroll"
                dark
                fixed
                bottom
                right
                color="secondary"
                @click="toTop"
            >
                <v-icon>mdi-arrow-up</v-icon>
            </v-btn>
        </v-scale-transition>
    </v-app>
</template>

<style>
    br
    {

    }
</style>

<script>
export default {
    name: "app",
    data() {
        return {
            fab: null,
            userId: sessionStorage.getItem("user-id"),
            color: "",
            flat: null,
            hospital: { id: 1025167, lat: 6.9214, lng: 122.075 },
            hospitals: [
                { id: 1025167, lat: 6.9214, lng: 122.075 },
                { id: 1025168, lat: 6.9225, lng: 122.0771 },
                { id: 1025169, lat: 6.9246, lng: 122.0712 },
                { id: 1025170, lat: 6.9237, lng: 122.0783 },
                { id: 1025171, lat: 6.9258, lng: 122.0794 }
            ],
            hospitalsLatLng: [
                { id: 1025167, lat: 6.9214, lng: 122.075 },
                { id: 1025168, lat: 6.9225, lng: 122.0771 },
                { id: 1025169, lat: 6.9246, lng: 122.0712 },
                { id: 1025170, lat: 6.9237, lng: 122.0783 },
                { id: 1025171, lat: 6.9258, lng: 122.0794 }
            ],
            //Google Maps Variables
            center: { lat: 6.9214, lng: 122.079 },
            address: { lat: 6.9214, lng: 122.079 },
            //Modals
            hospitalDialog: false
        };
    },

    methods: {
        onScroll(e) {
            if (typeof window === "undefined") return;
            const top = window.pageYOffset || e.target.scrollTop || 0;
            this.fab = top > 60;
        },

        toTop() {
            this.$vuetify.goTo(0);
        },

        fetchHospitals() {
            this.hospitalsLatLng = [];
            axios
                .get("/api/v1/nearbyhospitals", {
                    params: {
                        lat: this.center.lat,
                        lng: this.center.lng
                    }
                })
                .then(response => {
                    this.hospitals = response.data.nearby;
                    let hospitals = response.data.nearby;
                    hospitals.forEach(hospital => {
                        var position = {
                            ...hospital,
                            lat: hospital.latitude,
                            lng: hospital.longitude
                        };
                        this.hospitalsLatLng.push(position);
                    });
                    console.log(this.hospitalsLatLng);
                })
                .catch(error => {
                    console.log(error);
                })
                .finally(() => {
                    this.tableLoading = false;
                    this.componentOverlay = false;
                });
        },

        showHospital(id) {
            this.hospital = this.hospitals.find(x => x.id === id);
            console.log(this.hospital);
            this.hospitalDialog = true;
        },

        //Get Address to current location
        getUserGeolocation() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(
                    this.setUserGeolocation
                );
            } else {
                window.clearInterval(window.locationInterval);
                alert("Geolocation is not supported by this browser.");
            }
        },

        //Set Address to current location
        setUserGeolocation(position) {
            var UserGeolocationLatitude = position.coords.latitude;
            var UserGeolocationLongitude = position.coords.longitude;
            this.center = {
                lat: UserGeolocationLatitude,
                lng: UserGeolocationLongitude
            };
            this.address = this.center;
        },

        chipColor(status) {
            if (status == "RECIEVING") {
                return "success";
            } else {
                return "red";
            }
        }
    },

    watch: {
        fab(value) {
            if (value) {
                this.color = "#f8f9fa";
                this.flat = false;
            } else {
                this.color = "transparent";
                this.flat = true;
            }
        }
    },

    created() {
        this.toTop();
        const top = window.pageYOffset || 0;
        if (top <= 60) {
            this.color = "transparent";
            this.flat = true;
        }
        this.fetchHospitals();
    },
};
</script>
